### ISSUE TITLE
Letters to the contact section

### ISSUE THREAD

**Issue by gigisforza70** [wosys/AOSP_Dialer_AS#1]
Is it possible to add letters to the contact section?
As happens on almost all system dialers miui, oneplus, samsung, huawei, oppo, realme ..

maybe this can help:

https://github.com/reddit/IndicatorFastScroll

https://github.com/codexpedia/android_fast_scroll_with_alphabet/tree/master/fast_scroll_with_alphabet2

https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView

**Comment by wosys** [comment]
Hi @gigisforza70,

Glad you commented here.

This repo is just for me to learn Telephony. I'm a TeleFWK developer, who's fresh to this domain with about one year.
During work, I use command `make` most time(soong build method). However, based on AOSP code, I think every modules in `pacakges/apps/...` can be developed in Android Studio(IDE). Hence, I try to integrated Dialer code to AS.

With the help of Github & Internet, I successed.
Limited with my current knowledge, my aim is only to reproduce AOSP dialer in AS without any extension. 
Furthermore, I want to learn how to code this dialer.

**If you have energy and are willing to contribute to this repo, you can fork and develop.**
Maybe me or someone else will pay attention to your work in the future.🙂

// BR.
